url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "" # the name of your site, e.g. ACME Corp.

plugins:
  - jekyll-seo-tag

author:
  name: kartanus
  twitter: kartanusdev
twitter:
  username: kartanus
  card: summary_large_image
social:
  name: kartanus
  links:
    - https://twitter.com/kartanusdev
    - https://github.com/kartanusdev